### ISSUE TITLE
How do I make War Paint work on all of them?

### ISSUE THREAD

**Issue by HowToPlayMeow** [NotnHeavy/TF2-Attribute-Manager#1]
Settings I use

	"tf_weapon_sniperrifle" //Sniper Rifle
	{
		"damage bonus" 								"2"
		"aiming no flinch"								"1"
		"sniper only fire zoomed"						"1"
	}

War Paint weapons do not work. I want all Sniper weapons to be the same as my Settings.

**Comment by NotnHeavy** [comment]
I believe that's because stock war-painted weapons - in this case, the Sniper Rifle - fall under a different item definition index.

This wasn't intentional and I just changed this as a result, but `tf_weapon_sniperrifle` was treated as an internal weapon name and therefore it was substituted with the Sniper Rifle's item definition index (`14`) in the plugin itself, however a war-painted Sniper Rifle wouldn't fall under this.

From now on, `tf_weapon_sniperrifle` will instead be treated as an entity classname, and therefore any entity that uses this classname, which will include the other Sniper Rifle unlockables, except the Classic and the Bazaar Bargain - bizarrely enough :^), will be subject to the definition that has its name set to this, alongside the other weapon entity classnames.

If you still want this to apply to only the Sniper Rifle and its reskins/painted variant, you'll have to make a definition with a non-aligned tag (just name it whatever you want, so long as it isn't an actual weapon name or item definition index, I'd suggest `weapon_sniperrifle`), and then make a new definition for each of the stock Sniper Rifle item definition indexes (found [here](https://wiki.alliedmods.net/Team_fortress_2_item_definition_indexes)) that inherits from that non-aligned definition. I'll have to see if there's a way to automate this internally without literally making an array of names that map to others.

**Comment by HowToPlayMeow** [comment]
> I believe that's because stock war-painted weapons - in this case, the Sniper Rifle - fall under a different item definition index.
> 
> This wasn't intentional and I just changed this as a result, but `tf_weapon_sniperrifle` was treated as an internal weapon name and therefore it was substituted with the Sniper Rifle's item definition index (`14`) in the plugin itself, however a war-painted Sniper Rifle wouldn't fall under this.
> 
> From now on, `tf_weapon_sniperrifle` will instead be treated as an entity classname, and therefore any entity that uses this classname, which will include the other Sniper Rifle unlockables, except the Classic and the Bazaar Bargain - bizarrely enough :^), will be subject to the definition that has its name set to this, alongside the other weapon entity classnames.
> 
> If you still want this to apply to only the Sniper Rifle and its reskins/painted variant, you'll have to make a definition with a non-aligned tag (just name it whatever you want, so long as it isn't an actual weapon name or item definition index, I'd suggest `weapon_sniperrifle`), and then make a new definition for each of the stock Sniper Rifle item definition indexes (found [here](https://wiki.alliedmods.net/Team_fortress_2_item_definition_indexes)) that inherits from that non-aligned definition. I'll have to see if there's a way to automate this internally without literally making an array of names that map to others.

Thanks for the fix, it works :3
